author: Alex Rupérez
author_url: https://alexruperez.com
clean: true
copyright: Copyright (c) 2025 Alex Rupérez
github_file_prefix: https://github.com/alexruperez/SecurePropertyStorage/blob/master
github_url: https://github.com/alexruperez/SecurePropertyStorage
module: SecurePropertyStorage
root_url: https://alexruperez.github.io/SecurePropertyStorage
sourcekitten_sourcefile:
  - Docs/Storage.json
  - Docs/Keychain.json
  - Docs/UserDefault.json
  - Docs/Singleton.json
  - Docs/Inject.json
theme: fullwidth
